version: "3"
services:
  app:
    build: tododo-api
    env_file:
      - .env
    ports:
      - "3000:8000"
    volumes:
      - ./tododo-api/app:/tododo-api/app

  db:
    image: postgres:15.1-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
